spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: MySQL@1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

